services:
  - type: web
    name: advad-backend
    env: docker
    plan: starter
    dockerfilePath: Dockerfile
    branch: main
    startCommand: gunicorn app:app -w 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT --timeout 120
